### ISSUE TITLE
Error in using EntanglementForgingGroundStateSolver while freezing the orbitals

### ISSUE THREAD

**Issue by nirmal-aruvayi** [Qiskit-Extensions/circuit-knitting-toolbox#247]
Hello,

I'm following the tutorial on freezing the orbitals given in https://qiskit-extensions.github.io/circuit-knitting-toolbox/entanglement_forging/how-tos/freeze-orbitals.html

However, I'm getting an error of the following kind:
```
results = solver.solve(frozen_problem_mo)
  File /opt/conda/lib/python3.10/site-packages/circuit_knitting_toolbox/entanglement_forging/entanglement_forging_ground_state_solver.py:323 in solve
    result = EntanglementForgingResult.from_minimum_eigensolver_result(
  File /opt/conda/lib/python3.10/site-packages/qiskit_nature/second_q/problems/eigenstate_result.py:154 in from_minimum_eigensolver_result
    (_statevector_to_circuit(Statevector(raw_result.eigenstate)), None)
  File /opt/conda/lib/python3.10/site-packages/qiskit_nature/second_q/problems/eigenstate_result.py:32 in _statevector_to_circuit
    circ = QuantumCircuit(state.num_qubits)
  File /opt/conda/lib/python3.10/site-packages/qiskit/circuit/quantumcircuit.py:249 in __init__
    raise CircuitError(
CircuitError: "Circuit args must be Registers or integers. (['NoneType'] '(None,)' was provided)"
```

The following packages are being used:
 {'qiskit-terra': '0.24.0', 'qiskit-aer': '0.12.0', 'qiskit-ignis': None, 'qiskit-ibmq-provider': '0.20.2', 'qiskit': '0.43.0', 'qiskit-nature': '0.6.1', 'qiskit-finance': '0.3.4', 'qiskit-optimization': '0.5.0', 'qiskit-machine-learning': '0.6.0', 'circuit-knitting-toolbox':'0.2.0'}

I believe that the VQE optimization has run successfully, and the error comes at extracting the final state using `_stavector_to_circuit` method. The full code is posted for reference:

```python

import numpy as np

# Importing standard Qiskit libraries
from qiskit import QuantumCircuit, transpile, execute
from qiskit.tools.jupyter import *
from qiskit.visualization import *
from ibm_quantum_widgets import *
from qiskit_aer import AerSimulator

from qiskit.providers.aer import QasmSimulator

from qiskit_ibm_provider import IBMProvider

# Save account credentials.
# IBMProvider.save_account(token=MY_API_TOKEN)

# Load previously saved account credentials.
provider = IBMProvider()

import numpy as np

from qiskit.circuit import QuantumCircuit, Parameter
from qiskit_nature.second_q.drivers import PySCFDriver
from qiskit_nature.second_q.problems import ElectronicBasis
from qiskit_nature.second_q.formats import get_ao_to_mo_from_qcschema

from circuit_knitting_toolbox.entanglement_forging import (
    EntanglementForgingAnsatz,
)
from circuit_knitting_toolbox.utils import reduce_bitstrings

radius_1 = 0.958  # position for the first H atom
radius_2 = 0.958  # position for the second H atom
thetas_in_deg = 104.478  # bond angles.

H1_x = radius_1
H2_x = radius_2 * np.cos(np.pi / 180 * thetas_in_deg)
H2_y = radius_2 * np.sin(np.pi / 180 * thetas_in_deg)

driver = PySCFDriver(
    f"O 0.0 0.0 0.0; H {H1_x} 0.0 0.0; H {H2_x} {H2_y} 0.0", basis="sto6g"
)
full_problem_mo = driver.run()
full_problem_ao = driver.to_problem(basis=ElectronicBasis.AO)
# mo_problem = driver.to_problem(basis=ElectronicBasis.MO)
qcschema = driver.to_qcschema()

mo_coeff = get_ao_to_mo_from_qcschema(qcschema).coefficients.alpha["+-"]

from qiskit_nature.second_q.transformers import FreezeCoreTransformer

fc_transformer = FreezeCoreTransformer(remove_orbitals=[0,4])

frozen_problem_mo = fc_transformer.transform(full_problem_mo)

theta = Parameter("θ")

hop_gate = QuantumCircuit(2, name="Hop gate")
hop_gate.h(0)
hop_gate.cx(1, 0)
hop_gate.cx(0, 1)
hop_gate.ry(-theta, 0)
hop_gate.ry(-theta, 1)
hop_gate.cx(0, 1)
hop_gate.h(0)

theta_1, theta_2, theta_3, theta_4 = (
    Parameter("θ1"),
    Parameter("θ2"),
    Parameter("θ3"),
    Parameter("θ4"),
)

circuit_u = QuantumCircuit(5)
circuit_u.append(hop_gate.to_gate({theta: theta_1}), [0, 1])
circuit_u.append(hop_gate.to_gate({theta: theta_2}), [3, 4])
circuit_u.append(hop_gate.to_gate({theta: 0}), [1, 4])
circuit_u.append(hop_gate.to_gate({theta: theta_3}), [0, 2])
circuit_u.append(hop_gate.to_gate({theta: theta_4}), [3, 4])

# Set our bitstrings, and then reduce the chosen orbitals
orbitals_to_reduce = [0, 4]
bitstrings_u = [(1, 1, 1, 1, 1, 0, 0), (1, 0, 1, 1, 1, 0, 1), (1, 0, 1, 1, 1, 1, 0)]
reduced_bitstrings = reduce_bitstrings(bitstrings_u, orbitals_to_reduce)

ansatz = EntanglementForgingAnsatz(circuit_u=circuit_u, bitstrings_u=reduced_bitstrings)

from qiskit_ibm_runtime import QiskitRuntimeService, Options  # noqa: F401

# By default, use a local simulator to implement the Qiskit Runtime Primitives
service = None

# Uncomment the following line to instead use the Qiskit Runtime Service.
# service = QiskitRuntimeService(channel="ibm_quantum")

backend_names = ["simulator_statevector"] * 2

# If a single set of options are passed, it will be applied to all backends
options = [Options(execution={"shots": 1000}), Options(execution={"shots": 2000})]

import numpy as np
from qiskit.algorithms.optimizers import COBYLA, L_BFGS_B
from circuit_knitting_toolbox.entanglement_forging import (
    EntanglementForgingGroundStateSolver,
)

# optimizer = COBYLA(maxiter=100)
optimizer = L_BFGS_B(maxfun=15000, maxiter=100, ftol=2.220446049250313e-15, iprint=1, eps=1e-08, 
                            options={'disp': None, 'gtol':1e-05})
initial_point = np.zeros(ansatz.circuit_u.num_parameters)

solver = EntanglementForgingGroundStateSolver(
    ansatz=ansatz,
    optimizer=optimizer,
    service=service,
    backend_names=backend_names,
    options=options,
    initial_point=initial_point,
    #mo_coeff=mo_coeff,
)

results = solver.solve(frozen_problem_mo)
```

**Comment by garrison** [comment]
Thank you for the report.  I edited the issue to add markdown code blocks, so that it would be formatted correctly.  One note: It will be a lot easier for us to reproduce if you could add the appropriate `import` statements at the top of the code sample.

I am not sure if https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/issues/117#issuecomment-1536417246 is relevant, but it is one thing that came to mind when I first saw this issue.

**Comment by nirmal-aruvayi** [comment]
Thanks, Jim for editing the issue, it looks a lot more readable now. I have added the appropriate import statements at the top as well as some in between. 

To give more info, I could successfully apply freezing the orbitals to the same molecule when I'm using `circuit-knitting-toolbox==0.0.0` package that, I believe, uses an older version of qiskit-nature. About #117, it seems that it shows an implementation from a deprecated version of circuit-knitting-toolbox package, the function `EntanglementForgedConfig()` is not present in the latest version.

**Comment by caleb-johnson** [comment]
Hi, @nirmal-aruvayi , thanks for the report. I do believe this is related to #117 . Try passing `orbitals_to_reduce` directly into `EFGroundStateSolver`, as is shown in my response in #117, and let me know if it works as expected.

I will prioritize updating this how-to, as it is clearly misleading.

**Comment by caleb-johnson** [comment]
This was a combination of a bug and a confusing how-to. I have addressed this in #268

**Comment by nirmal-aruvayi** [comment]
Hi @caleb-johnson, I saw that you have fixed a bug in #268 that was preventing EFResults to be properly populated. Will you be updating this bug fix in the next release of `circuit-knitting-toolbox==0.2.1` or something? Becasuse, I tried passing `orbitals_to_reduce` argument to `EFGroundStateSolver` today while using `circuit-knitting-toolbox==0.2.0`, still the issue persists.

**Comment by caleb-johnson** [comment]
Hi @nirmal-aruvayi , yes this will be included in 0.3.0.

For now you can clone our repo, and `pip install .[pyscf]` from the root of the repo, and you should be able to use everything as intended. Let me know if you need an assist :)
